# Imagen base liviana
FROM node:22-alpine

# Instalar pnpm
RUN corepack enable

# Directorio de trabajo
WORKDIR /app

# Dependencias
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN pnpm install --frozen-lockfile

# Código fuente
COPY . .

# Scripts ejecutables
RUN chmod +x scripts/docker-entrypoint.dev.sh

# Entorno
ENV NODE_ENV=development

# Puerto Nest
EXPOSE 3000

CMD ["sh", "./scripts/docker-entrypoint.dev.sh"]
